name: GregsHikabrain
version: 1.0
author: gregwll
main: com.gregwll.hikabrain.Main
commands:
  matt:
  gm:
    description: more short command for gamemode command
  specleave:
    description: permit to leave the spectator mode

